POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Dota2 is very hard to madsterrrrrrrr",
    "author": "Jaakko Syr",
    "url": "https://www.dota2protracker.com/",
    "likes": 200
}